// ─────────────────────────────────────────────────────────────────────────────
// MOCK DATA — used when Sanity is not yet configured.
// Replace with real content via Sanity Studio once connected.
// ─────────────────────────────────────────────────────────────────────────────
import type { Episode, Person, Achievement } from '@/types'

export const MOCK_EPISODES: Episode[] = [
  {
    _id: 'ep-112',
    episodeNumber: 112,
    title: 'Ako sme vybudovali firmu za 10M€ bez vonkajšieho investora',
    slug: 'ep-112-firma-10m-bez-investora',
    publishedAt: '2026-03-15T08:00:00Z',
    category: 'Business',
    description: 'Martin Hudák hovorí o bootstrappingu, odmietnutých investoroch a rozhodnutiach, ktoré zmenili všetko.',
    guestName: 'Martin Hudák',
    guestTitle: 'CEO, Fintech SK',
    durationSeconds: 4320,
    spotifyUrl: 'https://open.spotify.com',
    appleUrl: 'https://podcasts.apple.com',
    youtubeUrl: 'https://youtube.com',
    isFeatured: true,
    tags: ['bootstrapping', 'fintech', 'funding'],
  },
  {
    _id: 'ep-111',
    episodeNumber: 111,
    title: 'Prečo sme vypálili 500k€ na marketing a čo sme sa naučili',
    slug: 'ep-111-500k-marketing',
    publishedAt: '2026-03-08T08:00:00Z',
    category: 'Marketing',
    description: 'Lucia Novák o digitálnom marketingu, brand buildingu a o tom, prečo čísla neklamú.',
    guestName: 'Lucia Novák',
    guestTitle: 'CMO, GrowthLab',
    durationSeconds: 3480,
    spotifyUrl: 'https://open.spotify.com',
    isFeatured: false,
    tags: ['marketing', 'growth', 'brand'],
  },
  {
    _id: 'ep-110',
    episodeNumber: 110,
    title: 'Vedenie tímu v kríze — čo skutočne funguje',
    slug: 'ep-110-vedenie-timu-kriza',
    publishedAt: '2026-03-01T08:00:00Z',
    category: 'Leadership',
    description: 'Tomáš Kováč o tom, ako udržal tím spolu počas najťažšieho obdobia firmy.',
    guestName: 'Tomáš Kováč',
    guestTitle: 'Founder, TeamForge',
    durationSeconds: 3900,
    spotifyUrl: 'https://open.spotify.com',
    isFeatured: false,
    tags: ['leadership', 'team', 'crisis'],
  },
  {
    _id: 'ep-109',
    episodeNumber: 109,
    title: 'Od nuly k prvým 1000 zákazníkom bez reklamy',
    slug: 'ep-109-prvy-1000-zakaznikov',
    publishedAt: '2026-02-22T08:00:00Z',
    category: 'Sales',
    description: 'Jana Horváth o organickom raste, word-of-mouth a produktovej stratégii pre B2C.',
    guestName: 'Jana Horváth',
    guestTitle: 'Co-founder, Shopify SK',
    durationSeconds: 2880,
    isFeatured: false,
    tags: ['sales', 'growth', 'b2c'],
  },
  {
    _id: 'ep-108',
    episodeNumber: 108,
    title: 'Ako vybudovať produkt, ktorý ľudia skutočne chcú',
    slug: 'ep-108-produkt-ktory-ludia-chcu',
    publishedAt: '2026-02-15T08:00:00Z',
    category: 'Product',
    description: 'Peter Blaho o product-market fit, user research a iteračnom vývoji.',
    guestName: 'Peter Blaho',
    guestTitle: 'CPO, DevTools Inc.',
    durationSeconds: 3660,
    isFeatured: false,
    tags: ['product', 'pmf', 'ux'],
  },
  {
    _id: 'ep-107',
    episodeNumber: 107,
    title: 'Mindset milionára — mýty a realita',
    slug: 'ep-107-mindset-milionara',
    publishedAt: '2026-02-08T08:00:00Z',
    category: 'Mindset',
    description: 'Otvárané o mentalite, návykoch a psychológii zakladateľa s Radoslavom Kišom.',
    guestName: 'Radoslav Kiš',
    guestTitle: 'Investor & Coach',
    durationSeconds: 4020,
    isFeatured: false,
    tags: ['mindset', 'habits', 'psychology'],
  },
]

export const MOCK_PERSON: Person = {
  name: 'Viktor Štefanák',
  tagline: 'Founder, Podcaster & Community Builder',
  tags: ['🎙 Podcaster', '🚀 Entrepreneur', '🤝 Community Builder', '📣 Speaker', '💡 Investor', '🇸🇰 Bratislava'],
  email: 'viktor@mentalitafoundera.sk',
  city: 'Bratislava',
  quote: 'Najlepší čas na začiatok bol včera. Druhý najlepší čas je dnes.',
  linkedinUrl: 'https://linkedin.com/in/viktorstefanak',
  instagramUrl: 'https://instagram.com/viktorstefanak',
  stats: [
    { value: '100+', label: 'Epizód' },
    { value: '50k', label: 'Poslucháčov' },
    { value: '#1', label: 'Startup podcast' },
  ],
}

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    _id: 'ach-1',
    title: 'Mentalita Foundera — 100+ epizód, #1 startup podcast SK',
    description: 'Podcast sa stal najpočúvanejším podnikateľským podcastom na Slovensku s najlepšími foundermi z regiónu.',
    year: '2025–2026',
    category: 'Media',
  },
  {
    _id: 'ach-2',
    title: 'Doers United — komunita 5 000+ aktívnych founderov',
    description: 'Vybudovanie najprepojiteľnejšej komunity zakladateľov v strednej Európe s pravidelnými eventmi a mentoringmi.',
    year: '2022–2024',
    category: 'Community',
  },
  {
    _id: 'ach-3',
    title: 'Prvý úspešný exit — B2B SaaS firma',
    description: 'Predaj prvej vlastnej firmy strategickému investorovi. Celý cyklus budovania a predaja biznisu.',
    year: '2019–2022',
    category: 'Business',
  },
  {
    _id: 'ach-4',
    title: 'Speaker na TEDx Bratislava & 50+ konferenciách',
    description: 'Prednášky o mentalite zakladateľov, podnikateľskej kultúre a budovaní odolnosti.',
    year: '2016–2019',
    category: 'Speaking',
  },
  {
    _id: 'ach-5',
    title: 'Prvá firma — štart podnikateľskej cesty',
    description: 'Prvý podnikateľský pokus, prvé zlyhania a lekcie, ktoré formovali každé ďalšie rozhodnutie.',
    year: '2014',
    category: 'Business',
  },
]
